### ISSUE TITLE
2 Error

### ISSUE THREAD

**Issue by SuperAdam47** [Dapro718/ItemNameDisplayer#1]
1)

[Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\item\Axe::setNameTagVisible()" (EXCEPTION) in "plugins/ItemNameDisplayer-master/src/Dapro718/ItemNameDisplayer/Main" at line 35

2.)

[Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\item\ItemBlock::getNameTag()" (EXCEPTION) in "plugins/ItemNameDisplayer-master/src/Dapro718/ItemNameDisplayer/Main" at line 28

**Comment by Dapro718** [comment]
Thanks for your feedback! This plugin is not finished neither tested. You will know when the plugin is done when the README is updated.

**Comment by SuperAdam47** [comment]
![image](https://user-images.githubusercontent.com/16169771/80553000-f8e23a80-89d0-11ea-9ca3-1af960e44589.png)
fixt
